language: node_js
sudo: required
before_script:
  - npm install -g polymer-cli
  - bower install
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
  - npm run lint
dist: trusty
notifications:
  slack:
    rooms:
      - secure: "N6pNTX2oGfxmNzK/0yjyMeowCPmyITTX75j29lw3H920fGWQXCmPJStQmL5vrN04KeZwdbNMpCMaS/n8A1fF3zG3wDk0G11zJ5M6fuwN5LqzEMpyYjcC7jr7WLcMWpeskwDDZ/WdHCbxWvLX7h3LVvqVuAD0YHk0blKQB0YQeq8vDUTRCF9+BMij+jYGdCqJDXKSjF4OAynGdzzvlgsF0oFYs9BNcramNXH2p2SBdhSTTGJeQnzuIt0qOfVdP+GbYu8472FvcBCfKnhpeKQG9Jye6Lm3JW1kzTxUeQER4DGW4JOPTqs6ouTUylzaO6HBN6Q+ea+zNNxw2W/DH5dOAC0NkPt8W2fLm8RWzTnJ/UFw/JHU8+/LxpPRhz6C6Ycp6NaYeYI5Yp346p6L/BbeGdz0GHd3qnI7FYxC5ebIlCmDy+V1gYhustUq8yfgGc8DrlcfORJ0NeYUYP4s4Z8oEkzKnO6n4R7dIXgqemvA1UgzPrFY/DnJ4+u8wqbNgsDsho4lhiwgOLlorxnZbd/jhoV/gZLT3tgXBKvu3C9n1MHV51DbD72ll52HCey72TQEjQmqNh7fvdwxLLQHk18LXjFPVsg0MCp2BrDTgQvj/WzOvOXCMV0rsvfmQN6e76K3TEudqkazsDTtKa3traLNrBlRkkVJnCy9TFuM4AnKkBc="
    on_success: always